--------------------------------------------------------
--  File created - Sunday-February-02-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNTDATA
--------------------------------------------------------

  CREATE TABLE "JB"."ACCOUNTDATA"
   (	"ID" NUMBER(*,0),
	"CREATE_DATE" DATE,
	"PASSWORD" VARCHAR2(50 BYTE),
	"EMAIL" VARCHAR2(50 BYTE),
	"PHONE" VARCHAR2(50 BYTE),
	"FULLNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENT
--------------------------------------------------------

  CREATE TABLE "JB"."EQUIPMENT"
   (	"ID" NUMBER(*,0),
	"EQUIMENT_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FILTR
--------------------------------------------------------

  CREATE TABLE "JB"."FILTR"
   ("ID" NUMBER(*,0),	
   "PUSHTAG" NUMBER(*,0),
    "FILTR_EQUIPMENT" NUMBER(*,0),
	"FILTR_LAYOUT" NUMBER(*,0),
    "FILTR_OFFERTYPE" NUMBER(*,0),
	"CRAWL_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOUSEITEM
--------------------------------------------------------

  CREATE TABLE "JB"."HOUSEITEM"
   (	"ID" NUMBER(*,0),
	"ADDRESS" VARCHAR2(50 BYTE),
	"CREATE_DATE" DATE,
	"UPDATE_DATE" DATE,
	"PRICE" NUMBER(10,0),
	"EQUIPMENT" NUMBER(*,0),
	"OFFERTYPE" NUMBER(*,0),
	"LAYOUT" NUMBER(*,0),
	"HOUSE_OWNER" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOUSE_OWNER
--------------------------------------------------------

  CREATE TABLE "JB"."HOUSE_OWNER"
   (	"OWNER_ID" NUMBER(*,0),
	"OWNER_EMAIL" VARCHAR2(50 BYTE),
	"OWNER_PHONE" VARCHAR2(50 BYTE),
	"FULLNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LAYOUT
--------------------------------------------------------

  CREATE TABLE "JB"."LAYOUT"
   (	"ID" NUMBER(*,0),
	"LAYOUT_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFFERTYPE
--------------------------------------------------------

  CREATE TABLE "JB"."OFFERTYPE"
   (	"ID" NUMBER(*,0),
	"OFFERTYPE_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
-- INSERTING into JB.ACCOUNTDATA

  Create table "JB".amenities (    

ID         SMALLINT                        NOT NULL,      

amenity varchar2(50) NOT NULL,        

CONSTRAINT PK_AMENITY PRIMARY KEY (ID) );  

  

GRANT SELECT ON AMENITIES TO STUDENT;  

  

GRANT DELETE,INSERT,SELECT,UPDATE ON AMENITIES TO DB;


  Create table "JB".HouseAmenities (
    HouseId NUMBER(*,0) not null,
    AmenityId SMALLINT not null );
  
  GRANT SELECT ON HouseAmenities TO STUDENT;  

  

GRANT DELETE,INSERT,SELECT,UPDATE ON HouseAmenities TO DB;


-- INSERTING into JB.EQUIPMENT

Insert into JB.equipment( id, equiment_name ) VALUES ( 2, '?áste?n? za?ízený' );
Insert into JB.equipment( id, equiment_name ) VALUES ( 1, 'Za?ízený' );
Insert into JB.equipment( id, equiment_name ) VALUES ( 0, 'Neza?ízený' );

-- INSERTING into JB.LAYOUT

Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (0,'Garsonka');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (2,'1+1');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (1,'1kk');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (3,'2kk');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (4,'2+1');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (5,'3kk');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (6,'3+1');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (7,'4kk');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (8,'4+1');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (9,'5kk');
Insert into JB.LAYOUT (ID,LAYOUT_NAME) values (10,'5+1');
-- INSERTING into JB.OFFERTYPE

Insert into JB.offertype( id, offertype_name ) VALUES ( 0, 'prodej' );
Insert into JB.offertype( id, offertype_name ) VALUES ( 1, 'dlouhodobý pronájem' );
Insert into JB.offertype( id, offertype_name ) VALUES ( 3, 'krátkodobý pronájem' );
Insert into JB.offertype( id, offertype_name ) VALUES ( 2, 'st?edn?dobý pronájem' );

Insert into JB.amenities(id, amenity) VALUES (1, 'ledni?ka');
Insert into JB.amenities(id, amenity) VALUES (2, 'televize');
Insert into JB.amenities(id, amenity) VALUES (3, 'wi-fi');
Insert into JB.amenities(id, amenity) VALUES (4, 'trouba');
Insert into JB.amenities(id, amenity) VALUES (5, 'l?ko');
Insert into JB.amenities(id, amenity) VALUES (6, 'vana');
Insert into JB.amenities(id, amenity) VALUES (7, 'klimatizace');


--------------------------------------------------------
--  DDL for Index AK_USER_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."AK_USER_EMAIL" ON "JB"."ACCOUNTDATA" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_USER_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."AK_USER_PHONE" ON "JB"."ACCOUNTDATA" ("PHONE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_OWNER_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."AK_OWNER_EMAIL" ON "JB"."HOUSE_OWNER" ("OWNER_EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_OWNER_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."AK_OWNER_PHONE" ON "JB"."HOUSE_OWNER" ("OWNER_PHONE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OFFERTYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_OFFERTYPE" ON "JB"."OFFERTYPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPEMNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_EQUIPEMNT" ON "JB"."EQUIPMENT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_HOUSEITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_HOUSEITEM" ON "JB"."HOUSEITEM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ACCOUNTDATA
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_ACCOUNTDATA" ON "JB"."ACCOUNTDATA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LAYOUT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_LAYOUT" ON "JB"."LAYOUT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OWNER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JB"."PK_OWNER" ON "JB"."HOUSE_OWNER" ("OWNER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OFFERTYPE
--------------------------------------------------------

  ALTER TABLE "JB"."OFFERTYPE" ADD CONSTRAINT "PK_OFFERTYPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."OFFERTYPE" MODIFY ("OFFERTYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "JB"."OFFERTYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "JB"."EQUIPMENT" ADD CONSTRAINT "PK_EQUIPEMNT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."EQUIPMENT" MODIFY ("EQUIMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "JB"."EQUIPMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNTDATA
--------------------------------------------------------

  ALTER TABLE "JB"."ACCOUNTDATA" ADD CONSTRAINT "AK_USER_PHONE" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."ACCOUNTDATA" ADD CONSTRAINT "AK_USER_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."ACCOUNTDATA" ADD CONSTRAINT "PK_ACCOUNTDATA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."ACCOUNTDATA" ADD CONSTRAINT "CKC_PASSWORD_ACCOUNTDATA" CHECK (LENGTH(PASSWORD) > 5) ENABLE;
  ALTER TABLE "JB"."ACCOUNTDATA" ADD CONSTRAINT "CKC_CREATE_DATE_ACCOUNTDATA" CHECK (
      CREATE_DATE >= TO_DATE('01.01.2017', 'DD.MM.YYYY')
    ) ENABLE;
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JB"."ACCOUNTDATA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOUSEITEM
--------------------------------------------------------

  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "PK_HOUSEITEM" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "CKC_UPDATE_DATE_HOUSEITEM" CHECK (UPDATE_DATE >= CREATE_DATE) ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "CKC_CREATE_DATE_HOUSEITEM" CHECK (
      CREATE_DATE >= TO_DATE('01.01.2017', 'DD.MM.YYYY')
    ) ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSEITEM" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSEITEM" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSEITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOUSE_OWNER
--------------------------------------------------------

  ALTER TABLE "JB"."HOUSE_OWNER" ADD CONSTRAINT "AK_OWNER_PHONE" UNIQUE ("OWNER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."HOUSE_OWNER" ADD CONSTRAINT "AK_OWNER_EMAIL" UNIQUE ("OWNER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."HOUSE_OWNER" ADD CONSTRAINT "PK_OWNER" PRIMARY KEY ("OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."HOUSE_OWNER" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSE_OWNER" MODIFY ("OWNER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSE_OWNER" MODIFY ("OWNER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "JB"."HOUSE_OWNER" MODIFY ("OWNER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LAYOUT
--------------------------------------------------------

  ALTER TABLE "JB"."LAYOUT" ADD CONSTRAINT "PK_LAYOUT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."LAYOUT" MODIFY ("LAYOUT_NAME" NOT NULL ENABLE);
  ALTER TABLE "JB"."LAYOUT" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table FILTR
--------------------------------------------------------

  ALTER TABLE "JB"."FILTR" ADD CONSTRAINT "PK_FILTR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JB"."FILTR" ADD CONSTRAINT "CKC_CRAWL_ID_FILTR" CHECK (CRAWL_ID >= 0) ENABLE;
  ALTER TABLE "JB"."FILTR" MODIFY ("CRAWL_ID" NOT NULL ENABLE);
  ALTER TABLE "JB"."FILTR" MODIFY ("PUSHTAG" NOT NULL ENABLE);
  ALTER TABLE "JB"."FILTR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FILTR
--------------------------------------------------------

  ALTER TABLE "JB"."FILTR" ADD CONSTRAINT "FK_FILTR_USER_ID" FOREIGN KEY ("PUSHTAG")
	  REFERENCES "JB"."ACCOUNTDATA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOUSEITEM
--------------------------------------------------------

  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "FK_HOUSEITEM_ID_EQUIPEMNT" FOREIGN KEY ("EQUIPMENT")
	  REFERENCES "JB"."EQUIPMENT" ("ID") ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "FK_HOUSEITEM_ID_LAYOUT" FOREIGN KEY ("LAYOUT")
	  REFERENCES "JB"."LAYOUT" ("ID") ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "FK_HOUSEITEM_ID_OFFERTYPE" FOREIGN KEY ("OFFERTYPE")
	  REFERENCES "JB"."OFFERTYPE" ("ID") ENABLE;
  ALTER TABLE "JB"."HOUSEITEM" ADD CONSTRAINT "FK_HOUSEITEM_ID_OWNER" FOREIGN KEY ("HOUSE_OWNER")
	  REFERENCES "JB"."HOUSE_OWNER" ("OWNER_ID") ENABLE;

  ALTER TABLE "JB"."HOUSEAMENITIES" ADD CONSTRAINT "fk_houseAmenities_Amenity" FOREIGN KEY ("AMENITYID")
	  REFERENCES "JB"."AMENITIES" ("ID") ENABLE;
  ALTER TABLE "JB"."HOUSEAMENITIES" ADD CONSTRAINT "fk_houseAmenities_House" FOREIGN KEY ("HOUSEID")
	  REFERENCES "JB"."HOUSEITEM" ("ID") ENABLE;

CREATE OR REPLACE VIEW HOUSES_SELECTED as 
	select ADDRESS, PRICE, houseitem.CREATE_DATE, HOUSE_OWNER.FULLNAME, HOUSE_OWNER.OWNER_EMAIL, HOUSE_OWNER.OWNER_PHONE, OFFERTYPE.OFFERTYPE_NAME, EQUIPMENT.EQUIMENT_NAME, LAYOUT.LAYOUT_NAME
from houseitem
JOIN
  FILTR ON houseitem.layout = FILTR_LAYOUT
	and offertype = FILTR_OFFERTYPE 
    and equipment = FILTR_EQUIPMENT
JOIN
  EQUIPMENT ON FILTR_EQUIPMENT = EQUIPMENT.ID
JOIN
  LAYOUT ON FILTR_LAYOUT = LAYOUT.ID
JOIN
  OFFERTYPE ON FILTR_OFFERTYPE = OFFERTYPE.ID
JOIN
  HOUSE_OWNER ON houseitem.HOUSE_OWNER = HOUSE_OWNER.OWNER_ID
;

GRANT SELECT ON HOUSES_SELECTED TO STUDENT;  

  

GRANT DELETE,INSERT,SELECT,UPDATE ON HOUSES_SELECTED TO DB;
